# Generated by Django 6.0.4 on 2026-04-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produce',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold_out', 'Sold Out'), ('low_stock', 'Low Stock'), ('discontinued', 'Discontinued')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='produce',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('piece', 'Piece'), ('bunch', 'Bunch'), ('sack', 'Sack'), ('tray', 'Tray'), ('litre', 'Litre')], default='kg', max_length=10),
        ),
    ]
