# Generated by Django 6.0.4 on 2026-04-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_produce_is_deleted_alter_produce_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
